config/routes.rb
Rails.application.routes.draw do
  
  #login e logout
  get 'welcome/login', as: 'login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  
  resources :perfils
  resources :tipo_vinculos
  resources :usuarios

  if ENV["SALAOREQUIP"].to_s  == "sala"
    resources :salas
  else 
    resources :salas, path: 'equipamentos'
  end

  resources :agendas
  resources :events
  resources :senha_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #inscricao e permissao
  get 'inscricao/:id' => 'agendas#inscricao', as: 'inscricao'
  get 'consulta/:id' => 'salas#consulta', as: 'consulta'
  get 'permissao/:id' => 'salas#permissao', as: 'permissao'

  get 'addadmin/:id/sala=:sala' => 'salas#addadmin', as: 'addadmin'
  get 'altersuper/:id/sala=:sala' => 'salas#altersuper', as: 'altersuper'
  get 'altersimples/:id/sala=:sala' => 'salas#altersimples', as: 'altersimples'
  get 'alterpendente/:id/sala=:sala' => 'salas#alterpendente', as: 'alterpendente'
  
  get 'removeracesso/:id/sala=:sala' => 'salas#removeracesso', as: 'removeracesso'

  get 'verinscritos/:id' => 'agendas#verinscritos', as: 'verinscritos'
  get 'inscreveoutro/:id/ag=:ag' => 'agendas#inscreveoutro', as: 'inscreveoutro'

  get 'alternegar/:id' => 'agendas#alternegar', as: 'alternegar'
  get 'alterinscrito/:id' => 'agendas#alterinscrito', as: 'alterinscrito'
  get 'alterusertipo/:id' => 'agendas#alterusertipo', as: 'alterusertipo'

  get 'listagem' => 'events#listagem', as: 'listagem'
  #get 'eventoagenda/:id' => 'events#eventoagenda', as: 'eventoagenda'

  get 'eventoagendalivres', to: 'events#eventoagendalivres', as: 'eventoagendalivres'

  get 'eventoagenda/:id', to: 'events#eventoagenda', as: 'eventoagenda'
  get 'resultagenda', to: 'events#resultagenda', as: 'resultagenda', defaults: { format: :json }

  get 'negarevento/:id' => 'events#negarevento', as: 'negarevento'
  get 'confirmarevento/:id' => 'events#confirmarevento', as: 'confirmarevento'

  get 'agendamentos/:id' => 'events#agendamentos', as: 'agendamentos'
  get 'deleteagend/:id' => 'events#deleteagend', as: 'deleteagend'

  get 'apresentasala' => 'events#apresentasala'

  get 'relgeral' => 'events#relgeral', as: 'relgeral'

  get 'login_ext' => 'session#new', as: 'login_ext'
  post 'login_ext' => 'session#create'
  get 'logout_ext' => 'session#destroy', as: 'logout_ext'


  #root 'welcome#login'

  root 'session#new'

  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


  def new
    #fabi correção
    logout_ext_url
    session[:login] = nil
  end

  def create

    externo = Usuario.find_by(emailPrincipalUsuario: params[:session][:email].downcase)
    if externo && externo.authenticate(params[:session][:password])
      login_ext externo
      @agendas = Agenda.where(apresentacaotelaini: true)
      #@inscricao = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? ", session[:login])
      #.select("usertipo, agenda_id, inscricaos.tipo")
      #redirect_to agendas_path
    else
      flash[:notice] = 'Usuário ou senha inválida'
      render 'new'
    end
  end

  def destroy
    logout_ext_url
    redirect_to root_path
  end

end

app/helpers/session_helper.rb
module SessionHelper

  def login_ext(externo)
    session[:login] = externo.loginUsuario
  end

  def logout_ext
    session.destroy
    @current_user = nil
  end

  # def current_user_ext
  #   @current_user ||= Usuario.find_by(id: session[:login])
  # end

  # def logged_in_ext
  #   !current_usuario_ext.nil?
  # end

end

app/views/session/create.html.erb
<h1>Boas-vindas</h1>

<h3>Agendas do ICB:</h3>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Observação</th>
      <th>Calendário</th>
      <th>Dados da inscrição</th>
      <th>Formulário extra</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.nome %></td>
        <td><%= agenda.observacao %></td>
        <td><%= link_to 'Calendário', eventoagenda_path(agenda), class: 'btn btn-success'  %>  </td>

        <% @inscricao = teminscricao(agenda.id) %>

        <% if @inscricao.empty? %>
          <td><%= link_to "Inscrever-se", inscricao_path(agenda), class: 'btn btn-light'  %> </td>
          <td><%= link_to "Formulário extra", agenda.reservadoformextra, class: 'btn btn-warning btn-lg' %></td>
          <td></td> 
        <% else %>
          <% @inscricao.each do |i| %>
                
            <% if i.tipo == "Pendente"  %>
              <td>Inscrição esperando autorização </td>
            <% elsif i.tipo == "Inscrito" %>
              <td>Inscrição realizada </td>                
            <% elsif i.tipo == "Negado"%>
              <td>Negado </td>             
            <% end %>

            <td><%= link_to "Formulário extra", agenda.reservadoformextra, class: 'btn btn-warning btn-lg' %></td>

            <% if i.usertipo == "Admin" or session[:admingeral] == true %>
              <td><%= link_to 'Inscritos', verinscritos_path(agenda), class: 'btn btn-light'  %></td>  
            <% else %>  
              <td></td> 
            <% end %>
            
          <% end %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/session/new.html.erb
<% if ENV["SOMENTEACESSOLOCAL"] == "false" %>

<h3> Login Externo </h3>
<%= form_for :session, url: login_ext_path do |f| %>
    <div class="form-group">
      <%= f.label :email, 'E-mail' %>
      <%= f.text_field :email, class: 'form-control',placeholder: 'Digite seu e-mail' %>
    </div>

    <div class="form-group">
      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Digite a senha' %>
    </div>

    <div class="actions">
      <%= f.submit 'Enviar', class: 'btn btn-primary active' %>
    </div>
<% end %>

<p><%= link_to "Registrar-se", new_usuario_path, class: 'btn btn-info' %> </p>

<!-- | <%= link_to "Esqueci minha senha", new_senha_reset_path, class: 'btn btn-success' %> -->

<hr>
<% end %>

<p></p>

<%= link_to "Login com número USP", login_path, class: 'btn btn-warning' %></p>

<p></p>


<td>
  <%= link_to eventoagendalivres_path, title: "Agendas", alt:"agenda", class: 'btn btn-default' do %>
    <%= image_tag "edit.svg" %> Visualizar agenda
  <% end %>
</td>

 