config/routes.rb
Rails.application.routes.draw do
  
  #login e logout
  get 'welcome/login', as: 'login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  
  resources :perfils
  resources :tipo_vinculos
  resources :usuarios

  if ENV["SALAOREQUIP"].to_s  == "sala"
    resources :salas
  else 
    resources :salas, path: 'equipamentos'
  end

  resources :agendas
  resources :events
  resources :senha_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #inscricao e permissao
  get 'inscricao/:id' => 'agendas#inscricao', as: 'inscricao'
  get 'consulta/:id' => 'salas#consulta', as: 'consulta'
  get 'permissao/:id' => 'salas#permissao', as: 'permissao'

  get 'addadmin/:id/sala=:sala' => 'salas#addadmin', as: 'addadmin'
  get 'altersuper/:id/sala=:sala' => 'salas#altersuper', as: 'altersuper'
  get 'altersimples/:id/sala=:sala' => 'salas#altersimples', as: 'altersimples'
  get 'alterpendente/:id/sala=:sala' => 'salas#alterpendente', as: 'alterpendente'
  
  get 'removeracesso/:id/sala=:sala' => 'salas#removeracesso', as: 'removeracesso'

  get 'verinscritos/:id' => 'agendas#verinscritos', as: 'verinscritos'
  get 'inscreveoutro/:id/ag=:ag' => 'agendas#inscreveoutro', as: 'inscreveoutro'

  get 'alternegar/:id' => 'agendas#alternegar', as: 'alternegar'
  get 'alterinscrito/:id' => 'agendas#alterinscrito', as: 'alterinscrito'
  get 'alterusertipo/:id' => 'agendas#alterusertipo', as: 'alterusertipo'

  get 'listagem' => 'events#listagem', as: 'listagem'
  #get 'eventoagenda/:id' => 'events#eventoagenda', as: 'eventoagenda'

  get 'eventoagendalivres', to: 'events#eventoagendalivres', as: 'eventoagendalivres'

  get 'eventoagenda/:id', to: 'events#eventoagenda', as: 'eventoagenda'
  get 'resultagenda', to: 'events#resultagenda', as: 'resultagenda', defaults: { format: :json }

  get 'negarevento/:id' => 'events#negarevento', as: 'negarevento'
  get 'confirmarevento/:id' => 'events#confirmarevento', as: 'confirmarevento'

  get 'agendamentos/:id' => 'events#agendamentos', as: 'agendamentos'
  get 'deleteagend/:id' => 'events#deleteagend', as: 'deleteagend'

  get 'apresentasala' => 'events#apresentasala'

  get 'relgeral' => 'events#relgeral', as: 'relgeral'

  get 'login_ext' => 'session#new', as: 'login_ext'
  post 'login_ext' => 'session#create'
  get 'logout_ext' => 'session#destroy', as: 'logout_ext'


  #root 'welcome#login'

  root 'session#new'

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  before_action :autenticado?, only: [:show, :edit, :update, :destroy, :index, :confirmarevento, :negarevento, :listagem]

  # GET /events
  # GET /events.json

  def index

  #  @events = Event.joins(:agendamentos).where("sala_id in (?)", salaspermitidas).select("events.id, Concat(events.title,' - ' ,events.registropara) as title, 
  #  events.start_date, events.end_date, events.timeini, events.timefim, agendamentos.data_inicio, agendamentos.data_fim, 
  #  agendamentos.hora_inicio, agendamentos.hora_fim, events.descricao, events.registropara, events.usuario_id, events.sala_id")

  #  o campo title concatenado é onde criamos o que vai ser mostrado no calendário
 
    @salas = Sala.joins(:permissaos).where(" permissaos.perfil_id in (1,2) and permissaos.usuario_id = ? ", current_user.id).select("salas.id")
 
    @ehadmindesala = false 
    @salas.each do |ehadmin|
      @ehadmindesala = true
    end

    @events = Event.joins(:agendamentos).joins(" inner join salas on events.sala_id = salas.id ")
    .where(" desmarcado = false and sala_id in (?)", salaspermitidas)
    .select("events.id, Concat(time_format(events.timeini, '%H:%i'), ' - ', time_format(events.timefim, '%H:%i'), ' - ', salas.nome,' - ' ,events.registropara ,' - ', if (pendente = 1, ' ⧗ EA', ' Ⓥ')) as title, 
    events.start_date, events.end_date, events.timeini, events.timefim, agendamentos.data_inicio, agendamentos.data_fim, 
    agendamentos.hora_inicio, agendamentos.hora_fim, events.descricao, events.registropara, events.usuario_id, events.sala_id, salas.cor")

    
    @salasdaagenda = Sala.where("id in (?)", salaspermitidas)

    #json.backgroundColor '#9297dd'
    #json.borderColor '#9297dd'

  end

  def resultagenda
    
    #considerar aqui as permissões 
    @events = Event.joins(:agendamentos).joins(" inner join salas on events.sala_id = salas.id ")
    .where("desmarcado = false and sala_id in (?)", @@salamostrar)
    .select("events.id, Concat(time_format(events.timeini, '%H:%i'), ' - ', time_format(events.timefim, '%H:%i'), ' - ', events.title,' - ' ,events.registropara ,' - ', if (pendente = 1, ' ⧗ EA', ' Ⓥ')) as title,  
    events.start_date, events.end_date, events.timeini, events.timefim, agendamentos.data_inicio, agendamentos.data_fim, 
    agendamentos.hora_inicio, agendamentos.hora_fim, events.descricao, events.registropara, events.usuario_id, events.sala_id, salas.cor")

  end

  def confirmarevento

    @event = Event.find_by(:id => params[:id])
    
    @event.pendente = false
    @event.save!

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.eventopendente(@event.id, @event.usuario_id, "Confirmado").deliver_now!

    redirect_to events_url, notice: 'Evento confirmado'

  end

  def negarevento

    @event = Event.find_by(:id => params[:id])

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.eventopendente(@event.id, @event.usuario_id, "Negado").deliver_now!
        
    @adminesuper = Permissao.where(perfil_id: [2, 1], sala_id: @event.sala_id)

    @adminesuper.each do |su|

      @usersuper = Usuario.find_by(id: su.usuario_id)
      ## Fim do contrato com a Nitronews
      ## NotificaMailer.notificaadmineventonegado(@event.id, @usersuper.id, "Negado").deliver_now!

    end 

    @event.destroy
    
    redirect_to events_url, notice: 'Evento negado'

  end

  def carrega_salas


    @permissao = Permissao.where(usuario_id: current_user.id, perfil_id: [1,2,3])

    salaspermitidas = Array.new
    @permissao.each do |p|
      salaspermitidas << p.sala_id
    end

    @salas = Sala.where(" id in (?) ", salaspermitidas)
  end 

  def salaspermitidas

    @salas = carrega_salas

    salaspermitidas = Array.new

    @salas.each do |a|
      salaspermitidas << a.id
    end

    return salaspermitidas
  end

  def listagem

    iddaagenda = params[:iddaagenda]

    if iddaagenda == "0"

      @events = Event.joins(:usuario)
      .where("desmarcado = false and sala_id in (?)", salaspermitidas)
      .select(" events.*, usuarios.nomeUsuario ").order("start_date desc")

    else
      @events = Event.joins(:usuario)
      .where("desmarcado = false and sala_id in (?)", salasdaagenda(iddaagenda))
      .select(" events.*, usuarios.nomeUsuario ").order("start_date desc")
    end 

  end

  def salasdaagenda(agenda)
 

    @permissao = Permissao.where(usuario_id: current_user.id, perfil_id: [1,2,3])

    salaspermitidas = Array.new
    @permissao.each do |p|
      salaspermitidas << p.sala_id
    end

    @salas = Sala.where(agenda_id: agenda)
    salaselecionada  = Array.new

    @salas.each do |a|

      if salaspermitidas.include?(a.id) == true
        salaselecionada << a.id
      end 
    end

    return salaselecionada
  end

  def eventoagenda
   
    @agendasel = params[:id]

    @@salamostrar = salasdaagenda(@agendasel)
    @salasdaagenda = Sala.where(:id => @@salamostrar)
    
    #@@salamostrar = salaspermitidas    
    #@salasdaagenda = Sala.where(:id => salaspermitidas)
    @dadosagenda = Agenda.where(:id => @agendasel)   
    
  end 

  def eventoagendalivres
    @@salamostrar = Sala.where("agenda_id in (select id from agendas where apresentacaotelaini = 1 and tipo = 'Publica')").select(" id ")
    
    @salasdaagenda = Sala.where(:id => @@salamostrar)
    
  end 

  def agendamentos

    @agendamentos = Agendamento.where(event_id: params[:id])
    @eventodoagendamento = Event.includes(:sala).find(params[:id])

  end

  def deleteagend

    @agendamento = Agendamento.find(params[:id])

    @evento = Event.find_by(id: @agendamento.event_id)

    @sala = Sala.find_by(id: @evento.sala_id)

    if @sala.avisoadmhoravaga == true

      @ini = @agendamento.data_inicio.strftime("%d/%m/%Y") + " - " + @agendamento.hora_inicio.strftime("%H:%M")
      @fim = @agendamento.data_fim.strftime("%d/%m/%Y") + " - " + @agendamento.hora_fim.strftime("%H:%M")

      @supers = Permissao.where(sala_id: @sala.id , perfil_id: 2)
      
      @supers.each do |s|
        @user = Usuario.find_by(id: s.usuario_id)

        ## Fim do contrato com a Nitronews
        ## NotificaMailer.avisohorariovago(@user.emailPrincipalUsuario, @ini, @fim, @sala.nome, @user.nomeUsuario).deliver_now!
      end 

    end

    @agendamento.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Agendamento na data escolhida apagado.' }
      format.json { head :no_content }
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new

    salasel = params[:idsala]

    @salas = Sala.joins(:permissaos).where(" permissaos.perfil_id in (1,2) and permissaos.usuario_id = ? and salas.id = ? ", current_user.id, salasel ).select("salas.id")
 
    @ehadmindesala = false 
    @salas.each do |ehadmin|
      @ehadmindesala = true
    end

    #@salas = salaspermitidas
    #@salas = Sala.where(" id in (?) ", salasel)

    @sala = Sala.find(salasel)

    # start_time = DateTime.parse("9 AM").to_i
    # start_interval = DateTime.parse("11 AM").to_i
    # end_interval = DateTime.parse("1 PM").to_i
    # end_time = DateTime.parse("3 PM").to_i

    #@values = (start_time..end_time).step(15.minutes).select{|t| t <= start_interval || t >= end_interval }

    if @sala.bloqforaintervalo == true 
      start_time = @sala.prihoraini.to_i
      start_interval = @sala.prihorafim.to_i
      end_interval = @sala.seghoraini.to_i
      end_time = @sala.seghorafim.to_i
      @values = (start_time..end_time).step(@sala.valorinterval.minutes).select{|t| t <= start_interval || t >= end_interval }
      @valuesfim = (start_time..end_time).step(@sala.valorinterval.minutes - 1).select{|t| t <= start_interval || t >= end_interval }

      @valuesfim.each do |hora|
        #print "-----"
        #print Time.at(hora).utc.to_datetime.strftime("%H:%M")

        if Time.at(hora).utc.to_datetime.strftime("%H:%M") == (@sala.prihorafim - 1).strftime("%H:%M")
          #Inclui a ultima hora do primeiro intervalo
          @valuesfim[@valuesfim.index(hora)] << @sala.prihorafim.to_i + (@sala.valorinterval.minutes - 1)
        end 

        if Time.at(hora).utc.to_datetime.strftime("%H:%M") == @sala.prihoraini.strftime("%H:%M")
          #Apaga a primeira hora definida
          @valuesfim.delete_at(@valuesfim.index(hora))
        end 
      end 
     
      #Inclui a ultima hora definida
      @valuesfim << @sala.seghorafim 

    else
      start_time = DateTime.parse("0 AM").to_i
      start_interval = DateTime.parse("11:55 AM").to_i
      end_interval = DateTime.parse("12 PM").to_i
      end_time = DateTime.parse("23:55 PM").to_i
      @values = (start_time..end_time).step(5.minutes).select{|t| t <= start_interval || t >= end_interval }
      @valuesfim = (start_time..end_time).step(5.minutes).select{|t| t <= start_interval || t >= end_interval }
    end

    @event = Event.new
  end

  # GET /events/1/edit
  def edit

    @salas = Sala.joins(:permissaos).where(" permissaos.perfil_id in (1,2) and permissaos.usuario_id = ? ", current_user.id).select("salas.id")
 
    @ehadmindesala = false 
    @salas.each do |ehadmin|
      @ehadmindesala = true
    end

    @sala = Sala.find(@event.sala_id)

    if @sala.bloqforaintervalo == true 
      start_time = @sala.prihoraini.to_i
      start_interval = @sala.prihorafim.to_i
      end_interval = @sala.seghoraini.to_i
      end_time = @sala.seghorafim.to_i
      @values = (start_time..end_time).step(@sala.valorinterval.minutes).select{|t| t <= start_interval || t >= end_interval }
      @valuesfim = (start_time..end_time).step(@sala.valorinterval.minutes - 1).select{|t| t <= start_interval || t >= end_interval }

      @valuesfim.each do |hora|
        #print "-----"
        #print Time.at(hora).utc.to_datetime.strftime("%H:%M")

app/helpers/events_helper.rb
module EventsHelper

    def extrair_primeiro_nome(nome_completo)
        # Divida o nome completo em palavras usando o espaço como delimitador
        palavras = nome_completo.split
        
        # O primeiro nome é a primeira palavra da lista
        primeiro_nome = palavras.first
        
        return primeiro_nome
    end

    def mostraanonimo(salaid)

        @sala = Sala.find(salaid)

        return @sala.anonimo
    end 

end

app/views/events/agendamentos.html.erb
<h1>Agendamentos</h1>

<table>
  <tr> <td>Título do Evento: <%=  @eventodoagendamento.title %> </td></tr>
  <tr> <td>Descrição: <%=  @eventodoagendamento.descricao %> </td></tr>
  <tr> <td>Registrado para:  <%=  @eventodoagendamento.registropara %> </td></tr>
  <tr> <td>Equipamento: <%=  @eventodoagendamento.sala.nome %> </td></tr>
</table>
<br>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>

      <th>Data inicial </th>
      <th>Hora inicial </th>
      <th>Data final </th>
      <th>Hora final</th>
      <th>Excluir</th>
    </tr>
  </thead>

  <tbody>
    <% @agendamentos.each do |a| %>
      <tr>
        <td><%= a.data_inicio.strftime("%d/%m/%Y") %></td>
        <td><%= a.hora_inicio.strftime("%H:%M") %></td>
        <td><%= a.data_fim.strftime("%d/%m/%Y") %></td>
        <td><%= a.hora_fim.strftime("%H:%M") %></td>
        <td><%= link_to 'Excluir', deleteagend_path(a), data: { confirm: 'Essa ação irá apagar somente este agendamento do evento. Você tem certeza ?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/events/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form', event: @event %>

<%= link_to 'Mostrar', @event, class: 'btn btn-info'  %> |
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/events/eventoagenda.html.erb
<!-- <%= link_to 'Novo Evento', new_event_path, class: 'btn btn-info'  %>
<br>
<br> -->

<%= link_to 'Lista de eventos', listagem_path(:iddaagenda => @agendasel), class: 'btn btn-warning'  %>

<br>
<br>

<% @dadosagenda.each do |agenda| %>
    <p><b><%= agenda.nome %></b> - <%= agenda.observacao %> </p> 
<% end %>

<br>
<p style="color:red;"><b>⧗ EA - Em ánalise </b></p>
<p style="color:green;"><b>Ⓥ - Confirmado</b> </p>


<div id="calendario"></div>

<br>

<table >
    <% agendaatual = "" %>
    <% @salasdaagenda.each do |sala|  %>
        <% if agendaatual == ""  or agendaatual != sala.agenda.nome  %>
        <tr>
            <td><b><%= sala.agenda.nome %> </b></td>
            <% agendaatual = sala.agenda.nome %>
        </tr> 
        <tr>
        <% end %>        
            <td> <%= link_to 'Marcar', new_event_path(:idsala => sala.id), class: 'btn btn-info'  %>  <%= sala.nome %> <input type="color" id="favcolor" name="favcolor" disabled value="<%= sala.cor %>">  </td>
        <% if agendaatual == ""  or agendaatual != sala.agenda.nome  %>
            </tr>
        <% end %>
    <% end %>
    
</table>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<!-- % if session[:admingeral] == true or @ehadmindesala == true %-->
    <%= link_to 'Lista de eventos', listagem_path(:iddaagenda => 0), class: 'btn btn-warning'  %>
<!--% end % -->

<br>
<br>
<p style="color:red;"><b>⧗ EA - Em ánalise </b></p>
<p style="color:green;"><b>Ⓥ - Confirmado</b> </p>

<div id="calendar"></div>

<br>

<table >
    <% agendaatual = "" %>
    <% @salasdaagenda.each do |sala|  %>
        <% if agendaatual == ""  or agendaatual != sala.agenda.nome  %>
        <tr>
            <td><b><%= sala.agenda.nome %> </b></td>
            <% agendaatual = sala.agenda.nome %>
        </tr> 
        <tr>
        <% end %>        
            <td> <%= link_to 'Marcar', new_event_path(:idsala => sala.id), class: 'btn btn-info'  %>  <%= sala.nome %> <input type="color" id="favcolor" name="favcolor" disabled value="<%= sala.cor %>">  </td>
        <% if agendaatual == ""  or agendaatual != sala.agenda.nome  %>
            </tr>
        <% end %>
    <% end %>
    
</table>

app/views/events/listagem.html.erb
<script type="text/javascript">
  $(document).ready(function() {
      $('#eventolista').dataTable ({
          "iDisplayLength": 10, 
          "bPaginate": true,    
          "sPaginationType":"full_numbers", 
          "bJQueryUI":true,
          "bLengthChange":false, 
          "ordering":     true, 
          "aaSorting":    [],  
          "oLanguage": { 
              "sInfo":              "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoFiltered":      "Filtrado de _MAX_ registros no total",
              "sInfoEmpty":         "Sem resultados",
              "sZeroRecords":       "Sem resultados",
              "sSearch":            "Buscar",
              "oPaginate": {
                  "sFirst":         "Primeiro",
                  "sPrevious":      "Anterior",
                  "sNext":          "Próximo",
                  "sLast":          "Ultimo"
              }
          }
      })
  })
</script>


<h1>Eventos</h1>

<table class="table table-bordered display" id="eventolista">
  <thead>
    <tr>
      <% if ENV["SALAOREQUIP"].to_s  == "sala" %>
        <th>Sala</th>
      <% else %>
        <th>Equipamento</th>
      <% end %>
      <th>Título</th>
      <th>Registrado para</th>
      <th>Usuário que marcou</th>
      <th>Data/Hora inicial</th>
      <th>Data/Hora final</th>

      <th>Ação</th>
      <th>Ação</th>
      <th>Ação</th>
      <th>Consulta</th>

    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.sala.nome %></td>
        <td><%= event.title %></td>
        <td><%= event.registropara %> </td>
        <td>
           
          <% if tempermissaosuperadmin(event.sala.id) %>
            <%= extrair_primeiro_nome(event.nomeUsuario) %> : <%= event.usuario.emailPrincipalUsuario %> - <%= event.usuario.numeroTelefoneFormatado %>  <%= event.usuario.tel_contato %>
          <% else %>
            <%= mostraanonimo(event.sala.id) == true ? "Anônimo" : extrair_primeiro_nome(event.nomeUsuario) %>
          <% end %>
          
        </td>
        <td><%= event.start_date.strftime("%d/%m/%Y") + " - " + event.timeini.strftime("%H:%M") %></td>
        <td><%= event.end_date.strftime("%d/%m/%Y") + " - " + event.timefim.strftime("%H:%M")  %></td>        
        <% if event.pendente == true %>
          <% if tempermissaosuperadmin(event.sala.id) %>
            <td><%= link_to 'Negar ', negarevento_path(event), data: { confirm: 'Essa ação irá apagar todos os agendamentos deste evento. Você tem certeza ?' } %> | <%= link_to 'Confirmar ', confirmarevento_path(event) %> </td>
          <% else %>
            <td style="color:red;">Esperando confirmação - ⧗ EA </td>
          <% end %>
        <% else %>
          <td style="color:green;"> Confirmado - Ⓥ </td>
        <% end %>
        <% if tempermissaosuperadmin(event.sala.id) %>
          <td><%= link_to 'Editar evento', edit_event_path(event), class: 'btn btn-warning'  %></td>
          <td><%= link_to 'Apagar evento', event, method: :delete, data: { confirm: 'Essa ação irá apagar todos os agendamentos deste evento. Você tem certeza ?' }, class: 'btn btn-danger' %></td>
          <td><%= link_to 'Agendamentos', agendamentos_path(event), class: 'btn btn-light'  %> </td>
        <% else %>
          <% if event.usuario_id == current_user.id %>
            <td><%= link_to 'Editar evento', edit_event_path(event), class: 'btn btn-warning'  %></td>

            <% if event.sala.permitiapagarevento == true %>
              <td><%= link_to 'Apagar evento', event, method: :delete, data: { confirm: 'Essa ação irá apagar todos os agendamentos deste evento. Você tem certeza ?' }, class: 'btn btn-danger' %></td>
            <% else %>
              <td></td>
            <% end %>
            <td></td>
          <% else %>
            <td></td>
            <td></td>
            <td></td> 
          <% end %>       
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render 'form', event: @event %>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/events/relgeral.html.erb
<%= form_tag(relgeral_path, method: "get") do  %>

    <h2>Consulta geral de eventos </h2>
    <br>
    <p>De: escolha a data
      <%= date_field_tag :valorde %>    
    </p>

    <p>Até: escolha a data
      <%= date_field_tag :valorate %>    
    </p>

    <p> Marcado <%= radio_button_tag :marcado, false %> ou Desmarcado  <%= radio_button_tag :marcado, true %> </p>
    <p> </p>

    <p>
      <% if ENV["SALAOREQUIP"].to_s  == "sala" %>
        <%= label_tag(:sala,  "Escolha a sala") %>
      <% else %>
        <%= label_tag(:sala,  "Escolha o equipamento") %>
      <% end %>      
      
      <%= select_tag :sala, options_from_collection_for_select(Sala.where(" id in (?)", carregarsalas), :id, :nome), class: 'chosen-select' %> 
    </p>

    <%= submit_tag "Enviar", class:"btn btn-default" %>

<% end %>

<br>

<h3>Relatório geral </h3>
<br>
<table  class="table table-bordered">
  <thead>
  <tr>
    <% if ENV["SALAOREQUIP"].to_s  == "sala" %>
      <th class="text-center">Sala</th>
    <% else %>
      <th class="text-center">Equipamento</th>
    <% end %>
    <th class="text-center"> Título </th>
    <th class="text-center"> Data inicial </th>
    <th class="text-center"> Hora inicial </th>
    <th class="text-center"> Data final </th>
    <th class="text-center"> Hora final </th>
    <th class="text-center"> Descrição </th>
    <th class="text-center"> Marcado por </th>

  </tr>
  </thead>
  <tbody>

  <% if @resultado == nil or @de == nil %>
    <h5>Nenhum dado foi encontrado ou selecionado </h5>
  <% else %>

    <% if @tipomarcacao == false %>
        <h5> Resultado da consulta: Eventos Marcados</h5>
    <% else %>
        <h5> Resultado da consulta: Eventos Desmarcados</h5>
    <% end %>

    <h5>De <%= Date.parse(@de).strftime("%d/%m/%Y") %> até <%= Date.parse(@ate).strftime("%d/%m/%Y") %> </h5>

    <% @resultado.each do |res| %>
    <tr>
        <td><%= res.nome %></td>
        <td><%= res.title %></td>
        <td><%= res.start_date.strftime("%d/%m/%Y") %></td>
        <td><%= res.timeini.strftime("%H:%M") %></td>
        <td><%= res.end_date.strftime("%d/%m/%Y") %></td> 
        <td><%= res.timefim.strftime("%H:%M") %></td>
        <td><%= res.descricao %></td>
        <td><%= res.nomeUsuario %></td>
    </tr>
    <% end %>
  <% end %>
  
  </tbody>
</table>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if ENV["SALAOREQUIP"].to_s  == "sala" %>
    <strong>Sala:</strong>
  <% else %>
    <strong>Equipamento:</strong>
  <% end %>

  <%= @event.sala.nome %>
</p>

<p>
  <strong>Título:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @event.descricao %>
</p>

<p>
  <strong>Registrado para:</strong>
  <%= @event.registropara %>
</p>

<p>
  <strong>Nome do usuário que registrou:</strong>
  <% if tempermissaosuperadmin(@event.sala.id) %>
    <%= extrair_primeiro_nome(@event.usuario.nomeUsuario) %> 
  <% else %>
    <%= mostraanonimo(@event.sala.id) == true ? "Anônimo" : extrair_primeiro_nome(@event.nomeUsuario) %>
  <% end %>
</p>


<% @agenda = infoagenda(@event.sala.agenda_id) %>

<% if @agenda.mostrainfouser == true %>
  <p>
    <strong>Informações de contato do usuário que registrou:</strong>
    <%= @event.usuario.emailPrincipalUsuario %> - <%= @event.usuario.numeroTelefoneFormatado %> - <%= @event.usuario.tel_contato %></td>
  </p>
<% else %>
  <% if tempermissaosuperadmin(@event.sala.id) %>
    <p>
      <strong>Informações de contato do usuário que registrou:</strong>
      <%= @event.usuario.emailPrincipalUsuario %> - <%= @event.usuario.numeroTelefoneFormatado %> - <%= @event.usuario.tel_contato %></td>
    </p>
  <% end %>
<% end %>


<p>
  <strong>Data/Hora inicial:</strong>
  <%= @event.start_date.strftime("%d/%m/%Y") + " - " + @event.timeini.strftime("%H:%M")   %>
</p>

<p>
  <strong>Data/Hora final:</strong>
  <%= @event.end_date.strftime("%d/%m/%Y") + " - " + @event.timefim.strftime("%H:%M") %>
</p>

<p>
  <strong>Status:</strong>
</p>

<% if @event.pendente == true %>
  <p style="color:red;"><b>Esperando confirmação - ⧗ EA</b> </p>
<% else %>
  <p style="color:green;"><b>Confirmado - Ⓥ</b></p>
<% end %>

<% if session[:admingeral] == true %>
  <%= link_to 'Editar', edit_event_path(@event), class: 'btn btn-warning' %> |
<% end %>
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>