config/routes.rb
Rails.application.routes.draw do
  
  #login e logout
  get 'welcome/login', as: 'login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  
  resources :perfils
  resources :tipo_vinculos
  resources :usuarios

  if ENV["SALAOREQUIP"].to_s  == "sala"
    resources :salas
  else 
    resources :salas, path: 'equipamentos'
  end

  resources :agendas
  resources :events
  resources :senha_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #inscricao e permissao
  get 'inscricao/:id' => 'agendas#inscricao', as: 'inscricao'
  get 'consulta/:id' => 'salas#consulta', as: 'consulta'
  get 'permissao/:id' => 'salas#permissao', as: 'permissao'

  get 'addadmin/:id/sala=:sala' => 'salas#addadmin', as: 'addadmin'
  get 'altersuper/:id/sala=:sala' => 'salas#altersuper', as: 'altersuper'
  get 'altersimples/:id/sala=:sala' => 'salas#altersimples', as: 'altersimples'
  get 'alterpendente/:id/sala=:sala' => 'salas#alterpendente', as: 'alterpendente'
  
  get 'removeracesso/:id/sala=:sala' => 'salas#removeracesso', as: 'removeracesso'

  get 'verinscritos/:id' => 'agendas#verinscritos', as: 'verinscritos'
  get 'inscreveoutro/:id/ag=:ag' => 'agendas#inscreveoutro', as: 'inscreveoutro'

  get 'alternegar/:id' => 'agendas#alternegar', as: 'alternegar'
  get 'alterinscrito/:id' => 'agendas#alterinscrito', as: 'alterinscrito'
  get 'alterusertipo/:id' => 'agendas#alterusertipo', as: 'alterusertipo'

  get 'listagem' => 'events#listagem', as: 'listagem'
  #get 'eventoagenda/:id' => 'events#eventoagenda', as: 'eventoagenda'

  get 'eventoagendalivres', to: 'events#eventoagendalivres', as: 'eventoagendalivres'

  get 'eventoagenda/:id', to: 'events#eventoagenda', as: 'eventoagenda'
  get 'resultagenda', to: 'events#resultagenda', as: 'resultagenda', defaults: { format: :json }

  get 'negarevento/:id' => 'events#negarevento', as: 'negarevento'
  get 'confirmarevento/:id' => 'events#confirmarevento', as: 'confirmarevento'

  get 'agendamentos/:id' => 'events#agendamentos', as: 'agendamentos'
  get 'deleteagend/:id' => 'events#deleteagend', as: 'deleteagend'

  get 'apresentasala' => 'events#apresentasala'

  get 'relgeral' => 'events#relgeral', as: 'relgeral'

  get 'login_ext' => 'session#new', as: 'login_ext'
  post 'login_ext' => 'session#create'
  get 'logout_ext' => 'session#destroy', as: 'logout_ext'


  #root 'welcome#login'

  root 'session#new'

  
end

app/models/agenda.rb
class Agenda < ApplicationRecord
    has_many :salas

    has_many :inscricaos, :class_name => 'Inscricao', dependent: :delete_all
    has_many :usuarios, :through => :inscricaos

end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  # GET /agendas.json
  def index

    @inscricao = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? ", session[:login]).select("usertipo, agenda_id")
    if session[:admingeral] == true
      @agendas = Agenda.all
    else      
      @agendas = carrega_agendas
    end   

  end

  def inscreveoutro

    iduser = params[:id]
    agenda = params[:ag]
    @tipoagenda = Agenda.find_by(id: agenda)
    @valida = Inscricao.find_by(usuario_id: iduser, agenda_id: agenda)

    if @valida.nil?

      @insc = Inscricao.new
      @insc.usuario_id = iduser
      @insc.agenda_id = agenda
      @insc.tipo = "Inscrito"
      @insc.usertipo = "Simples"
      @insc.save!

      ## Fim do contrato com a Nitronews
      ##NotificaMailer.permissaoagendauser(agenda, iduser).deliver_now!
    
      addpermissao(agenda, iduser)

    end 
    
  end 


  def inscricao

    if session[:login] == nil      
      redirect_to login_path
    else  

      @agenda = params[:id]

      @tipoagenda = Agenda.find_by(id: @agenda)

      @valida = Inscricao.find_by(usuario_id: current_user.id, agenda_id:@agenda)

      if @valida.nil?

        if @tipoagenda.tipo == 'Publica'

          if @tipoagenda.validaextra == true

            @insc = Inscricao.new
            @insc.usuario_id = current_user.id
            @insc.agenda_id = @agenda
            @insc.tipo = "Pendente"
            @insc.usertipo = "Simples"
            @insc.save!

            ## Fim do contrato com a Nitronews
            # 1 - Admin
            # 2 - Supervisor  
            # @salasx = Sala.where(agenda_id: @agenda)
        
            # @salasx.each do |s| 
        
            #   @super = Permissao.where(perfil_id: [2, 1], sala_id: s.id)
        
            #   @super.each do |su|
        
            #     @usersuper = Usuario.find_by(id: su.usuario_id)            #    
            #     ## NotificaMailer.permissaoagenda(@tipoagenda.nome, current_user.id, @usersuper.emailPrincipalUsuario).deliver_now!
            #   end

            # end

            ## Fim do contrato com a Nitronews
            ## NotificaMailer.permissaoagendauser(@agenda, current_user.id).deliver_now!
          
            @confirmado = false
            print "Aqui 1**********************"
          else

            @insc = Inscricao.new
            @insc.usuario_id = current_user.id
            @insc.agenda_id = @agenda
            @insc.tipo = "Inscrito"
            @insc.usertipo = "Simples"
            @insc.save!

            ## Fim do contrato com a Nitronews
            ## NotificaMailer.permissaoagendauser(@agenda, current_user.id).deliver_now!
          
            addpermissao(@agenda, current_user.id)
            @confirmado = true
            print "Aqui 2*************************"
          end 

        else

          @insc = Inscricao.new
          @insc.usuario_id = current_user.id
          @insc.agenda_id = @agenda
          @insc.tipo = "Pendente"
          @insc.usertipo = "Simples"
          @insc.save!

          ## Fim do contrato com a Nitronews
          # 1 - Admin
          # 2 - Supervisor  
          # @salasx = Sala.where(agenda_id: @agenda)
      
          # @salasx.each do |s| 
      
          #   @super = Permissao.where(perfil_id: [2, 1], sala_id: s.id)
      
          #   @super.each do |su|
      
          #     @usersuper = Usuario.find_by(id: su.usuario_id)

          #     ## NotificaMailer.permissaoagenda(@tipoagenda.nome, current_user.id, @usersuper.emailPrincipalUsuario).deliver_now!
          #   end

          # end

          ## Fim do contrato com a Nitronews
          ## NotificaMailer.permissaoagendauser(@agenda, current_user.id).deliver_now!

          @confirmado = false

          print "Aqui 3**************************"
        end

      else
        @confirmado = true
        print "Aqui 4 ***********************"
      end

    end  
    
  end  

  def verinscritos

    @agenda = params[:id]

    @insc = Inscricao.joins(:usuario).joins(:agenda).where(agenda_id: @agenda)

    @souadmin = false 
    @insc.each do |inscricao|
      if inscricao.usertipo == "Admin"
        if inscricao.usuario_id == current_user.id
          @souadmin = true 
        end
      end 
    end

    #select * from usuarios where id not in (select usuario_id from inscricaos where agenda_id = 5);
    @userseminsc = Usuario.where("id not in (select usuario_id from inscricaos where agenda_id = ? )", @agenda) 

  end

  #fazer rotina
  def alterusertipo 
  
    @insc = Inscricao.find_by(:id => params[:id])
    
    if @insc.usertipo == "Simples"
      @insc.usertipo = "Admin"
    else 
      @insc.usertipo = "Simples"
    end 

    @insc.save!

  end 


  def alternegar

    @insc = Inscricao.find_by(:id => params[:id])
    
    @insc.tipo = "Negado"
    @insc.usertipo = ""
    @insc.save!

    # apagar as permissões para todas as salas da agenda em questão...
    @salasdaagenda = Sala.where(agenda_id: @insc.agenda)

    @salasdaagenda.each do |s|
    
      @permissao = Permissao.find_by(usuario_id: @insc.usuario_id, sala_id: s.id)

      @permissao.destroy! unless @permissao.nil?

    end   

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.inscricaoagenda(@insc.id, "Rejeitada").deliver_now!

  end

  def alterinscrito
    
    @insc = Inscricao.find_by(:id => params[:id])

    @insc.tipo = "Inscrito"
    @insc.usertipo = "Simples"
    @insc.save!

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.inscricaoagenda(@insc.id, "Aprovada").deliver_now!

  end

  ### Adiciona usuario em salas com permissao automatica
  def addpermissao(agenda, usuario)

    @salas = Sala.where(agenda_id: agenda, permissaoauto: true)

    @salas.each do |s|

      @p = Permissao.new
      @p.usuario_id = usuario
      @p.sala_id = s.id
      @p.perfil_id = Perfil.find_by(:nomeperfil => 'Simples').id

      @p.save!
    end 

  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @agenda }
      else
        format.html { render :new }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to @agenda, notice: 'Agenda foi alterada com sucesso.' }
        format.json { render :show, status: :ok, location: @agenda }
      else
        format.html { render :edit }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url, notice: 'Agenda foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agenda_params
      params.require(:agenda).permit(:nome, :apresentacaotelaini, :observacao, :tipo, :validaextra, :usertipo, :reservadoformextra, :mostrainfouser)
    end
end

=begin

 Eu preciso criar sempre uma agenda ;
 Ela precisa ter pelo menos uma sala;
 E tambem um supervisor 
 
=end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<%= form_with(model: agenda, local: true) do |form| %>
  <% if agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, 'Nome' %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :apresentacaotelaini, 'Apresentar na tela inicial' %>
    <%= form.check_box :apresentacaotelaini %>
  </div>

  <div class="field">
    <%= form.label :tipo,'Selecione o tipo de agenda' %>
    <%= form.select :tipo,([['Publica'],['Privada']]) %>
  </div>

  <div class="field">
    <%= form.label :validaextra, 'Exige validação de campos extra' %>
    <%= form.check_box :validaextra %>
  </div>

  <div class="field">
    <%= form.label :reservadoformextra, 'Formulário extra de dados' %>
    <%= form.text_field :reservadoformextra %>
  </div>
 
  <div class="field">
    <%= form.label :observacao, 'Observações gerais' %>
    <%= form.text_field :observacao %>
  </div>

  <div class="field">
    <%= form.label :mostrainfouser, 'Apresentar informações do usuário' %>
    <%= form.check_box :mostrainfouser %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar' %>
  </div>
<% end %>

app/views/agendas/alterinscrito.html.erb
<h1>Usuário inscrito!</h1>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/alternegar.html.erb
<h1>Usuário negado acesso a agenda!</h1>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/alterusertipo.html.erb
<h1>Acesso modificado para essa agenda!</h1>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/edit.html.erb
<h1>Editar Agenda</h1>

<%= render 'form', agenda: @agenda %>

<%= link_to 'Mostrar', @agenda, class: 'btn btn-light' %> |
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agendas - ICB</h1>

<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Apresentar na tela inicial</th>
      <th>Mostra informações do usuário que registrou</th>
      <th>Exige validação extra</th>
      <th>Formulário extra</th>
      <th>Observação</th>
      <th>Tipo</th>
      <th>Inscrição</th>     
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.nome %></td>
        <td><%= agenda.apresentacaotelaini == true ? "Sim" : "Não" %></td>
        <td><%= agenda.mostrainfouser == true ? "Sim" : "Não" %></td>
        <td><%= agenda.validaextra == true ? "Sim" : "Não" %></td>
        <td><%= link_to "Formulário extra", agenda.reservadoformextra, class: 'btn btn-warning btn-lg'  %> </td>
        
        <td><%= agenda.observacao %></td>
        <td><%= agenda.tipo %></td>

        <% @inscricao = teminscricao(agenda.id) %>

        <% if @inscricao.empty? %>
          <td><%= link_to "Inscrever-se", inscricao_path(agenda), class: 'btn btn-info'  %> </td>
        <% else %>
          <% @inscricao.each do |i| %>
                
            <% if i.tipo == "Pendente"  %>
              <td>Inscrição esperando autorização </td>
            <% elsif i.tipo == "Inscrito" %>
              <td>Inscrito </td>
            <% elsif i.tipo == "Negado"%>
              <td>Negado </td>             
            <% end %>

          <% end %>
        <% end %>

        <% if ENV["SALAOREQUIP"].to_s  == "sala" %>
          <td><%= link_to 'Salas', consulta_path(agenda), class: 'btn btn-light'  %> </td>
        <% else %>
          <td><%= link_to 'Equipamentos', consulta_path(agenda), class: 'btn btn-light'  %> </td>
        <% end %>

        <td><%= link_to 'Informações', agenda, class: 'btn btn-light'  %></td>
        <td><%= link_to 'Calendário', eventoagenda_path(agenda), class: 'btn btn-success'  %>  </td>
   
        

        <% if session[:admingeral] == true %>
            <td><%= link_to 'Inscritos', verinscritos_path(agenda), class: 'btn btn-light'  %></td>    
            <td><%= link_to 'Editar', edit_agenda_path(agenda), class: 'btn btn-warning' %></td>  
            <td><%= link_to 'Apagar', agenda, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-danger' %></td> 
        <% else %>
          <% @inscricao.each do |i| %>
            <% if i.agenda_id == agenda.id %>
              <% if i.usertipo == "Admin" %>
                  <td><%= link_to 'Inscritos', verinscritos_path(agenda), class: 'btn btn-light'  %></td>    
                  <td><%= link_to 'Editar', edit_agenda_path(agenda), class: 'btn btn-warning' %></td>          
                  <td></td>                  
              <% else %>
                  <td></td>
                  <td></td>
                  <td></td>
              <% end %>  
            <% end %>                  
          <% end %>                 
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if session[:admingeral] == true %>
  <%= link_to 'Nova Agenda', new_agenda_path, class: 'btn btn-info' %>
<% end %>

app/views/agendas/inscreveoutro.html.erb
<h1>Usuário inscrito!</h1>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/inscricao.html.erb
<% if @confirmado == true %>
    <h2>Inscrição na agenda <%= @tipoagenda.nome %> realizada!</h2>
<% else %>
    <h2>Pedido de inscrição na agenda <%= @tipoagenda.nome %> foi feito com sucesso. Inscrição pendente aguardando manifestação do supervisor.</h2>
<% end %>   

<h3><%= @tipoagenda.observacao %></h3>

<br>

<% if @tipoagenda.validaextra == true %>
<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <p class="lead">Essa agenda exige o preenchimento de outro formulário para uso.</p>
        <p class="lead">Favor preencher esse <b><%= link_to "Formulário extra", @tipoagenda.reservadoformextra, class: 'btn btn-warning btn-lg' %> </b> </p>
    </div>    
</div>    
<% end %>

app/views/agendas/new.html.erb
<h1>Nova Agenda</h1>

<%= render 'form', agenda: @agenda %>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @agenda.nome %>
</p>

<p>
  <strong>Apresentar na tela inicial:</strong>
  <%= @agenda.apresentacaotelaini == true ? "Sim" : "Não" %>
</p>

<p>
  <strong>Mostra informações do usuário que registrou:</strong>
  <%= @agenda.mostrainfouser == true ? "Sim" : "Não" %>
</p>

<p>
  <strong>Exige validação extra:</strong>
  <%= @agenda.validaextra == true ? "Sim" : "Não" %>
</p>

<p>
  <strong>Formulário extra de validação:</strong>
  <%= link_to "Formulário extra", @agenda.reservadoformextra, class: 'btn btn-warning btn-lg' %>
</p>

<p>
  <strong>Observação:</strong>
  <%= @agenda.observacao %>
</p>

<p>
  <strong>Tipo de agenda:</strong>
  <%= @agenda.tipo %>
</p>

<% if session[:admingeral] == true %> 
  <%= link_to 'Editar', edit_agenda_path(@agenda), class: 'btn btn-warning'  %> |
<% end %>
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/agendas/verinscritos.html.erb
<h1>Minhas Agendas ICB</h1>

<h3>Inscritos </h3>
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Agenda</th>
      <th>Usuário</th>
      <th>E-mail</th>
      <th>Status da inscrição</th>
      <th>Data da inscrição</th>
      <th>Tipo de Usuário</th>
      <% if session[:admingeral] == true or @souadmin == true %>
        <th colspan="2">Alterar status</th>
        <th>Tipo de Usuário </th>
      <% end %>     
    </tr>
  </thead>

  <tbody>
    <% @insc.each do |ins| %>
      <tr>
        <td><%= ins.agenda.nome %></td>
        <td><%= ins.usuario.nomeUsuario %></td>
        <td><%= ins.usuario.emailPrincipalUsuario %></td>
        <td><%= ins.tipo %></td>
        <td><%= ins.created_at.strftime("%d/%m/%Y")  %> </td>
        <td><%= ins.usertipo %></td>
        <% if session[:admingeral] == true or @souadmin == true %>
          <td><%= link_to 'Negar', alternegar_path(:id => ins.id), class: 'btn btn-danger' %> </td>
          <td><%= link_to 'Inscrever', alterinscrito_path(:id => ins.id), class: 'btn btn-success' %> </td>        
          <td><%= link_to 'Trocar', alterusertipo_path(:id => ins.id), class: 'btn btn-info' %> </td>
        <% end %>                
      </tr>
    <% end %>
  </tbody>
</table>

<% if session[:admingeral] == true or @souadmin == true %>

  <h3>Não inscritos </h3>
  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr>
        <th>Usuário</th>
        <th>E-mail</th>
        <th>Tipo de Usuário</th>
        <% if session[:admingeral] == true or @souadmin == true %>
          <th>Inscrição</th>
        <% end %>     
      </tr>
    </thead>

    <tbody>
      <% @userseminsc.each do |usersem| %>
        <tr>
          <td><%= usersem.nomeUsuario %></td>
          <td><%= usersem.emailPrincipalUsuario %></td>
          <td><%= usersem.tipoUsuario %></td>
          <% if session[:admingeral] == true or @souadmin == true %>
            <td><%= link_to 'Inscrever', inscreveoutro_path(:id => usersem.id, :ag => @agenda), class: 'btn btn-success' %> </td>        
          <% end %>                
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>   