config/routes.rb
Rails.application.routes.draw do
  
  #login e logout
  get 'welcome/login', as: 'login'
  get 'welcome/callback'
  get 'logout' => 'welcome#destroy', as: 'logout'
  
  resources :perfils
  resources :tipo_vinculos
  resources :usuarios

  if ENV["SALAOREQUIP"].to_s  == "sala"
    resources :salas
  else 
    resources :salas, path: 'equipamentos'
  end

  resources :agendas
  resources :events
  resources :senha_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #inscricao e permissao
  get 'inscricao/:id' => 'agendas#inscricao', as: 'inscricao'
  get 'consulta/:id' => 'salas#consulta', as: 'consulta'
  get 'permissao/:id' => 'salas#permissao', as: 'permissao'

  get 'addadmin/:id/sala=:sala' => 'salas#addadmin', as: 'addadmin'
  get 'altersuper/:id/sala=:sala' => 'salas#altersuper', as: 'altersuper'
  get 'altersimples/:id/sala=:sala' => 'salas#altersimples', as: 'altersimples'
  get 'alterpendente/:id/sala=:sala' => 'salas#alterpendente', as: 'alterpendente'
  
  get 'removeracesso/:id/sala=:sala' => 'salas#removeracesso', as: 'removeracesso'

  get 'verinscritos/:id' => 'agendas#verinscritos', as: 'verinscritos'
  get 'inscreveoutro/:id/ag=:ag' => 'agendas#inscreveoutro', as: 'inscreveoutro'

  get 'alternegar/:id' => 'agendas#alternegar', as: 'alternegar'
  get 'alterinscrito/:id' => 'agendas#alterinscrito', as: 'alterinscrito'
  get 'alterusertipo/:id' => 'agendas#alterusertipo', as: 'alterusertipo'

  get 'listagem' => 'events#listagem', as: 'listagem'
  #get 'eventoagenda/:id' => 'events#eventoagenda', as: 'eventoagenda'

  get 'eventoagendalivres', to: 'events#eventoagendalivres', as: 'eventoagendalivres'

  get 'eventoagenda/:id', to: 'events#eventoagenda', as: 'eventoagenda'
  get 'resultagenda', to: 'events#resultagenda', as: 'resultagenda', defaults: { format: :json }

  get 'negarevento/:id' => 'events#negarevento', as: 'negarevento'
  get 'confirmarevento/:id' => 'events#confirmarevento', as: 'confirmarevento'

  get 'agendamentos/:id' => 'events#agendamentos', as: 'agendamentos'
  get 'deleteagend/:id' => 'events#deleteagend', as: 'deleteagend'

  get 'apresentasala' => 'events#apresentasala'

  get 'relgeral' => 'events#relgeral', as: 'relgeral'

  get 'login_ext' => 'session#new', as: 'login_ext'
  post 'login_ext' => 'session#create'
  get 'logout_ext' => 'session#destroy', as: 'logout_ext'


  #root 'welcome#login'

  root 'session#new'

  
end

app/models/sala.rb
class Sala < ApplicationRecord
  belongs_to :agenda
  has_many :events

  has_many :permissaos, :class_name => 'Permissao', dependent: :delete_all
  has_many :perfils, :through => :permissaos

  has_many :permissaos, :class_name => 'Permissao', dependent: :delete_all
  has_many :usuarios, :through => :permissaos

end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]
  before_action :autenticado?

  def consulta
    @agenda = params[:id]
    
    @inscricao = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? ", session[:login]).select("usertipo, agenda_id")

    @salas = Sala.where(agenda_id: @agenda)
  end   

  def permissao
    @sala = params[:id]

    @permitidos = Permissao.joins(:usuario).joins(:perfil)
    .joins(" inner join tipo_vinculos on usuarios.id = tipo_vinculos.usuario_id ").where(sala_id: @sala)
    .select("permissaos.usuario_id, nomeUsuario, emailPrincipalUsuario,  tipoVinculo, nomeSetor, siglaUnidade, sala_id, nomeperfil")

    @permitidosext = Permissao.joins(:usuario).joins(:perfil).where(sala_id: @sala).where(' tipoUsuario= "Externo" ')
    .select("permissaos.usuario_id, nomeUsuario, emailPrincipalUsuario,  'Externo' as tipoVinculo, 'Externo' as nomeSetor, 'Externo' as siglaUnidade, sala_id, nomeperfil")

    @usuarios = Permissao.where(sala_id: @sala).select("usuario_id")

    @negados = Usuario.joins(:tipo_vinculos).where('usuarios.id not in (?) ', @usuarios)
    .select("usuarios.id, nomeUsuario, emailPrincipalUsuario, tipoVinculo, nomeSetor, siglaUnidade")

    @negadosext = Usuario.where('id not in (?) and tipoUsuario = "EXTERNO"', @usuarios)
    .select(" id, nomeUsuario, emailPrincipalUsuario, 'Externo' as tipoVinculo, 'Externo' as nomeSetor, 'Externo' as siglaUnidade ")
    
  end 

  def salvaperfil(perfil, sala, user)
    
    @permissao = Permissao.find_by(sala_id: sala, usuario_id: user)

    if @permissao.nil?
      @p = Permissao.new
      @p.usuario_id = user
      @p.sala_id = sala
      @p.perfil_id = perfil

      @p.save!
    
      return true 
    else
      @permissao.perfil_id = @perfil 
      @permissao.save!

      return false
    end 
    
  end

  def addadmin
 
    @perfil = Perfil.find_by(:nomeperfil => 'Admin').id
    @registrado = salvaperfil(@perfil, params[:sala], params[:id])

    ## Fim do contrato com a Nitronews
    ##NotificaMailer.permissaosala(params[:id], params[:sala], "Administrador").deliver_now!

  end 

  def altersuper
    @perfil = Perfil.find_by(:nomeperfil => 'Supervisor').id
    @registrado = salvaperfil(@perfil, params[:sala], params[:id])
    
    ## Fim do contrato com a Nitronews
    ##NotificaMailer.permissaosala(params[:id], params[:sala], "Supervisor").deliver_now!

  end  

  def altersimples
    @perfil = Perfil.find_by(:nomeperfil => 'Simples').id
    @registrado = salvaperfil(@perfil, params[:sala], params[:id])

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.permissaosala(params[:id], params[:sala], "Simples").deliver_now!

  end   


  def alterpendente
    @perfil = Perfil.find_by(:nomeperfil => 'Pendente').id
    @registrado = salvaperfil(@perfil, params[:sala], params[:id])

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.permissaosala(params[:id], params[:sala], "Pendente").deliver_now!
    
    ## Fim do contrato com a Nitronews
    #Notifica admins    
    #@admins = Sala.joins(:permissaos).where(id: params[:sala])
    #          .where(" permissaos.perfil_id in (1,2) ").select("salas.*, permissaos.usuario_id")
    #@admins.each do |adm|
      ## NotificaMailer.permissaosalaadm(adm.usuario_id, params[:sala], "Pendente", params[:id]).deliver_now!  
    #end 
  end   

  def removeracesso

    @permissao = Permissao.find_by(sala_id: params[:sala], usuario_id: params[:id])
    @permissao.destroy!

    ## Fim do contrato com a Nitronews
    ## NotificaMailer.remocaosala(params[:id], params[:sala]).deliver_now!

  end 

  # GET /salas
  # GET /salas.json
  def index
    @salas = carrega_salas
    #select * from permissaos p inner join perfils f on p.perfil_id = f.id where usuario_id = 1 and nomeperfil = 'Admin'
    #@salacomoadmin = Permissao.joins(:perfil).where(usuario_id: current_user.id, nomeperfil: "Admin")
    if params[:sala_id].present?
      @salas = Sala.where(id: params[:sala_id])
    end

    @salas 

    salaspermitidas = Array.new

    @salas.each do |a|
        salaspermitidas << a.id
    end

    @salasescondidas = Sala.where(permissaoauto: false).where("id not in (?)", salaspermitidas)

    @inscricao = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? ", session[:login]).select("usertipo, agenda_id")

  end

  # GET /salas/1
  # GET /salas/1.json
  def show
  end

  # GET /salas/new
  def new

    #Alterado botão Novo equipamento
    @agenda = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? and usertipo = 'Admin'", session[:login]).select("agenda_id, nome")

    @sala = Sala.new

  end

  # GET /salas/1/edit
  def edit

    #Alterado botão Novo equipamento
    @agenda = Inscricao.joins(:usuario).joins(:agenda).where("usuarios.loginUsuario = ? and usertipo = 'Admin'", session[:login]).select("agenda_id, nome")

  end

  # POST /salas
  # POST /salas.json
  def create
    @sala = Sala.new(sala_params)

    respond_to do |format|
      if @sala.save

        if @sala.permissaoauto == true 
          puts "Permissao automatica OKOKOKOKOKOKOKOKOK"
          addpermissao(@sala.agenda_id, @sala.id)
        end 

        format.html { redirect_to @sala, notice: 'Equipamento foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @sala }
      else
        format.html { render :new }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

#### Nova sala com permissao automatica
  def addpermissao(agenda, sala)
    @insc = Inscricao.where(agenda_id: agenda).select('usuario_id') 

    @insc.each do |i|
      @p = Permissao.new
      @p.usuario_id = i.usuario_id
      @p.sala_id = sala
      @p.perfil_id = Perfil.find_by(:nomeperfil => 'Simples').id

      @p.save!
    end  

  end  

  # PATCH/PUT /salas/1
  # PATCH/PUT /salas/1.json
  def update
    respond_to do |format|
      if @sala.update(sala_params)
        if @sala.permissaoauto == true
          alterpermissao(@sala.id, @sala.agenda_id)
        end  
        format.html { redirect_to @sala, notice: 'Equipamento foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @sala }
      else
        format.html { render :edit }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

### Alteraçao de sala 
  def alterpermissao(sala, agenda)
    @insc = Inscricao.where(agenda_id: agenda).select('usuario_id') 

    @insc.each do |i|
    
      @permissao = Permissao.find_by(sala_id: sala, usuario_id: i.usuario_id)

      if @permissao.nil?
        @p = Permissao.new
        @p.usuario_id = i.usuario_id
        @p.sala_id = sala
        @p.perfil_id = Perfil.find_by(:nomeperfil => 'Simples').id
  
        @p.save!
      end 

    end  

  end  

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy

    
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url, notice: 'Equipamento foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sala_params
      params.require(:sala).permit(:nome, :cor, :permissaoauto, :observacao, :confirmacao, :agenda_id, :avisoadmhoravaga, :limiteqtdeuso, :limitehoras, :bloqforaintervalo ,:prihoraini, :prihorafim, :seghoraini, :seghorafim, :valorinterval, :disablefds, :permitiapagarevento, :anonimo)
    end
end

app/helpers/salas_helper.rb
module SalasHelper

    def tempermissaosuperadmin(sala_id)

        @valor = Sala.joins(:permissaos).where(id: sala_id).where(" permissaos.perfil_id in (1,2) and permissaos.usuario_id = ? ", current_user.id)

        return @valor.exists?

    end

    def jasolicitouacesso(sala_id)

        @valor = Sala.joins(:permissaos).where(id: sala_id).where(" permissaos.perfil_id = 4 and permissaos.usuario_id = ? ", current_user.id)

        return @valor.exists?

    end

end

app/views/salas/addadmin.html.erb
<% if @registrado == true %>
    <h1>Perfil cadastrado!</h1>
<% else %>
    <h1>Perfil alterado! </h1>
<% end %>   

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/salas/alterpendente.html.erb
<% if ENV["SALAOREQUIP"].to_s  == "sala" %>
    <h3>Seu pedido para fazer uso dessa sala foi feito. Aguarde o parecer do administrador.</h3>
<% else %>
    <h3>Seu pedido para fazer uso desse equipamento foi feito. Aguarde o parecer do administrador.</h3>
<% end %>

<br>
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/salas/altersimples.html.erb
<% if @registrado == true %>
    <h1>Perfil cadastrado!</h1>
<% else %>
    <h1>Perfil alterado! </h1>
<% end %>    

<%= link_to 'Voltar', :back, class: 'btn btn-dark active'%>

app/views/salas/altersuper.html.erb
<% if @registrado == true %>
    <h1>Perfil cadastrado!</h1>
<% else %>
    <h1>Perfil alterado! </h1>
<% end %>   

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/salas/edit.html.erb
<% if ENV["SALAOREQUIP"].to_s  == "sala" %>
    <h1>Editar sala</h1>
<% else %>
    <h1>Editar Equipamento</h1>
<% end %>

<%= render 'form', sala: @sala %>

<%= link_to 'Mostrar', @sala, class: "btn btn-primary" %> |
<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/salas/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
      $('#sala').dataTable ({
          "iDisplayLength": 10, 
          "bPaginate": true,    
          "sPaginationType":"full_numbers", 
          "bJQueryUI":true,
          "bLengthChange":false, 
          "ordering":     true, 
          "aaSorting":    [],  
          "oLanguage": { 
              "sInfo":              "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoFiltered":      "Filtrado de _MAX_ registros no total",
              "sInfoEmpty":         "Sem resultados",
              "sZeroRecords":       "Sem resultados",
              "sSearch":            "Buscar",
              "oPaginate": {
                  "sFirst":         "Primeiro",
                  "sPrevious":      "Anterior",
                  "sNext":          "Próximo",
                  "sLast":          "Ultimo"
              }
          }
      })
  })
</script>

<p id="notice"><%= notice %></p>

<% if ENV["SALAOREQUIP"].to_s  == "sala" %>
  <h1>Salas permitidas o acesso ou liberadas anteriormente </h1>
<% else %>
  <h1>Equipamentos permitidos o acesso ou liberados anteriormente </h1>
<% end %>

<table class="table table-bordered display" id="sala">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cor</th>
      <th>Permissão Automática</th>
      <th>Observação</th>
      <th>Confirmação do Agendamento</th>
      <th>Avisar horário vago</th>
      <th>Limite de uso</th>
      <th>Bloquear fora do intervalo</th>
      <th>Pertence a agenda</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.nome %></td>
        <td><input type="color" id="favcolor" name="favcolor" disabled value="<%= sala.cor %>"></td>
        <td><%= sala.permissaoauto == true ? "Sim" : "Não" %></td>
        <td><%= sala.observacao %></td>
        <td><%= sala.confirmacao == true ? "Exige confirmar" : "Não exige confirmar" %></td>
        <td><%= sala.avisoadmhoravaga == true ? "Sim" : "Não" %> </td>
        <td><%= sala.limiteqtdeuso == true ? "Sim" : "Não" %></td>
        <td><%= sala.bloqforaintervalo == true ? "Sim" : "Não" %></td>
        <td><%= sala.agenda.nome %></td>
        <td><%= link_to 'Mostrar', sala, class: "btn btn-primary" %></td>

        <% if session[:admingeral] == true %>
          <td><%= link_to 'Editar', edit_sala_path(sala), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Permissão', permissao_path(sala), class: 'btn btn-light' %> </td>
          <td><%= link_to 'Apagar', sala, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %></td>          
        <% elsif tempermissaosuperadmin(sala.id)%>
          <td><%= link_to 'Editar', edit_sala_path(sala), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Permissão', permissao_path(sala), class: 'btn btn-light' %> </td>
          <td></td>
        <% else %>
          <td></td>
          <td></td>
          <td></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if ENV["SALAOREQUIP"].to_s  == "sala" %>
  <h1>Salas que necessitam autorização para uso </h1>
<% else %>
  <h1>Equipamentos que necessitam autorização para uso </h1>
<% end %>


<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cor</th>
      <th>Permissão Automática</th>
      <th>Observação</th>
      <th>Confirmação do Agendamento</th>
      <th>Avisar horário vago</th>
      <th>Limite de uso</th>
      <th>Bloquear fora do intervalo</th>
      <th>Pertence a agenda</th>
      <th></th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @salasescondidas.each do |sala| %>
      <tr>
        <td><%= sala.nome %></td>
        <td><input type="color" id="favcolor" name="favcolor" disabled value="<%= sala.cor %>"></td>
        <td><%= sala.permissaoauto == true ? "Sim" : "Não" %></td>
        <td><%= sala.observacao %></td>
        <td><%= sala.confirmacao == true ? "Exige confirmar" : "Não exige confirmar" %></td>
        <td><%= sala.avisoadmhoravaga == true ? "Sim" : "Não" %> </td>
        <td><%= sala.limiteqtdeuso == true ? "Sim" : "Não" %></td>
        <td><%= sala.bloqforaintervalo == true ? "Sim" : "Não" %></td>
        <td><%= sala.agenda.nome %></td>
        <td><%= link_to 'Mostrar', sala, class: "btn btn-primary" %></td>
        <td></td>
        <% if jasolicitouacesso(sala.id) %>
          <td>Acesso solicitado. Aguarde</td>
        <% else %>
          <td><%= link_to 'Solicitar acesso', alterpendente_path(:id => current_user.id, :sala => sala.id), class: 'btn btn-default' %> </td>     
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <% if session[:admingeral] == true %>
  <%= link_to 'Novo Equipamento', new_sala_path, class: 'btn btn-info' %>
<% end %>   -->

<!-- Alterado botão Novo equipamento-->
<% @inscricao.each do |i| %>
    <% if i.usertipo == "Admin" or session[:admingeral] == true %>
      <%= link_to 'Incluir novo', new_sala_path, class: 'btn btn-info' %> 
      <% break %>
  <% end %>                  
<% end %>   
<br>

app/views/salas/new.html.erb
<% if ENV["SALAOREQUIP"].to_s  == "sala" %>
    <h1>Novo sala</h1>
<% else %>
    <h1>Nova equipamento</h1>
<% end %>

<%= render 'form', sala: @sala %>

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>

app/views/salas/permissao.html.erb
<h1>Permitidos / Solicitado acesso </h1>
<% @sala_atual = @sala%>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Vínculo</th>
            <th>Setor</th>
            <th>Unidade</th>
            <th>E-mail</th>
            <th>Perfil Atual</th>
            
            <th colspan="2">Trocar para ?</th>
            <th>Remover acesso</th>
        </tr>
    </thead>
  <tbody>
    <% @permitidos.each do |p| %>
        <tr>

            <td><%= p.nomeUsuario %> </td>
            <td><%= p.tipoVinculo %> </td>
            <td><%= p.nomeSetor %> </td>
            <td><%= p.siglaUnidade %></td>
            <td><%= p.emailPrincipalUsuario %> </td>
            <td><%= p.nomeperfil %></td>  

            <% if p.nomeperfil == 'Admin' %>
                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        

            <% elsif p.nomeperfil == 'Supervisor' %>
                <td><%= link_to 'Admin', addadmin_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-info' %> </td>
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
            
            <% elsif p.nomeperfil == 'Simples' %>
                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>   
                <td><%= link_to 'Admin', addadmin_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-info' %> </td>           
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>   

            <% elsif p.nomeperfil == 'Pendente' %>

                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>   
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                         
            <% end %>

        </tr>
    <% end %>
  </tbody>


  <tbody>
    <% @permitidosext.each do |p| %>
        <tr>

            <td><%= p.nomeUsuario %> </td>
            <td><%= p.tipoVinculo %> </td>
            <td><%= p.nomeSetor %> </td>
            <td><%= p.siglaUnidade %></td>
            <td><%= p.emailPrincipalUsuario %> </td>
            <td><%= p.nomeperfil %></td>  

            <% if p.nomeperfil == 'Admin' %>
                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        

            <% elsif p.nomeperfil == 'Supervisor' %>
                <td><%= link_to 'Admin', addadmin_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-info' %> </td>
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
            <% elsif p.nomeperfil == 'Simples' %>
                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>   
                <td><%= link_to 'Admin', addadmin_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-info' %> </td>           
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                         

            <% elsif p.nomeperfil == 'Pendente' %>

                <td><%= link_to 'Supervisor', altersuper_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-warning' %> </td>   
                <td><%= link_to 'Simples', altersimples_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                        
                <td><%= link_to 'Remover', removeracesso_path(:id => p.usuario_id, :sala => p.sala_id), class: 'btn btn-danger' %> </td>                                                     
            <% end %>
        </tr>
    <% end %>
  </tbody>

</table>    

<h1>Usuários sem Permissão </h1>

<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Vínculo</th>
            <th>Setor</th>
            <th>Unidade</th>
            <th>E-mail</th>
            <th colspan="3">Cadastrar como </th>
        </tr>
    </thead>
  <tbody>
    <% @negados.each do |n| %>
        <tr>
            <td><%= n.nomeUsuario %> </td>
            <td><%= n.tipoVinculo %> </td>
            <td><%= n.nomeSetor %> </td>
            <td><%= n.siglaUnidade %></td>
            <td><%= n.emailPrincipalUsuario %> </td>
            <td><%= link_to 'Admin', addadmin_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-info' %> </td>
            <td><%= link_to 'Supervisor', altersuper_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-warning' %> </td>
            <td><%= link_to 'Simples', altersimples_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-danger' %> </td>            
        </tr>
    <% end %>
  </tbody>

  <tbody>
    <% @negadosext.each do |n| %>
        <tr>
            <td><%= n.nomeUsuario %> </td>
            <td><%= n.tipoVinculo %> </td>
            <td><%= n.nomeSetor %> </td>
            <td><%= n.siglaUnidade %></td>
            <td><%= n.emailPrincipalUsuario %> </td>
            <td><%= link_to 'Admin', addadmin_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-info' %> </td>
            <td><%= link_to 'Supervisor', altersuper_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-warning' %> </td>
            <td><%= link_to 'Simples', altersimples_path(:id => n.id, :sala => @sala_atual), class: 'btn btn-danger' %> </td>            
        </tr>
    <% end %>
  </tbody>

</table> 

<%= link_to 'Voltar', :back, class: 'btn btn-dark active' %>